### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by bet0x** [protosam/hostcontrol#2]
Hello, i been working on CP's and Linux for long. I wanted to collaborate with the project if possible. I was thinking on this features:

- CP With or without X feature, means i can use other software installed. Separated Mail Server or Stuff like that.
- Cluster installation
- Backups
- Let's Encrypt support
- When i add a new user i want to add a website and create everything automatically.

There is any forum or something to collaborate or talk?

**Comment by protosam** [comment]
Hey Alberto,

Working with some other people on this would be cool. I've never actually collaborated on projects before, so I'm not sure what the workflow is like, though I'm open to figuring something out.

Some thoughts on what you mentioned, 
- I think the next version will address your first point. It's going to be a more modular system.
- The next version will allow for a more redundant DNS setup and possibly a more robust MariaDB implementation
- Backups are definitely a yes once feature implementation is done.
- In regards to encryption, I have apache proxying to Hostcontrol so that it can be accessed over SSL. If implementing SSL with Macaron is doable, that can be implemented too.
- In the "Add User" portion in the webpanel, more options were slated to permit that. I just never got around to it. 

If you want to hit me up on Google Hangouts my email is sync.demon@gmail.com

Right now I'm rebuilding HC2 to support a multi-server environment actually. I'm taking hostcontrol and restructuring the core of it so that I can better build for multi-server solutions. It's being rewritten from the ground up. 

Some pain points that I have with the current version are as follows:

-  HC2 will need to control a fleet of servers while only needing to be installed on one server. The Core 4 will be deployable together on one server or separately between multiple servers (Apache|MySQL|DNS|Email)

- The code is sloppy and cobbled together. HC2 is going to be better structured so that it can be properly documented. I have functions in places they don't even need to be

- The API was an afterthought, so the new design needs to implement API first followed by Web Panel controls.

Those are my first short-term goals at the moment.

I definitely wouldn't mind discussing it more.

Regards,
Sam

**Comment by kpetku** [comment]
I would be interested in collaborating too.  I sent you an invite on hangouts.
